packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  '@tanstack/react-query': ^5.60.5
  '@trpc/client': ^11.0.0-rc.638
  '@trpc/react-query': ^11.0.0-rc.638
  '@trpc/server': ^11.0.0-rc.638
  eslint: ^9.15.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.15
  typescript: ^5.6.3
  zod: ^3.23.8
catalogs:
  react18:
    '@types/react': ^18.3.12
    '@types/react-dom': ^18.3.1
    react: 18.3.1
    react-dom: 18.3.1
