packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  '@tanstack/react-query': ^5.62.8
  '@trpc/client': ^11.0.0-rc.666
  '@trpc/react-query': ^11.0.0-rc.666
  '@trpc/server': ^11.0.0-rc.666
  eslint: ^9.17.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.17
  typescript: ^5.7.2
  zod: ^3.24.1
catalogs:
  react19:
    '@types/react': ^19.0.2
    '@types/react-dom': ^19.0.2
    react: 19.0.0
    react-dom: 19.0.0
