packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  '@tanstack/react-query': ^5.62.7
  '@trpc/client': ^11.0.0-rc.660
  '@trpc/react-query': ^11.0.0-rc.660
  '@trpc/server': ^11.0.0-rc.660
  eslint: ^9.16.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.16
  typescript: ^5.7.2
  zod: ^3.24.1
catalogs:
  react18:
    '@types/react': ^18.3.16
    '@types/react-dom': ^18.3.5
    react: 18.3.1
    react-dom: 18.3.1
