/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SitemapDotxmlRouteImport } from "./routes/sitemap[.]xml";
import { Route as LlmsDottxtRouteImport } from "./routes/llms[.]txt";
import { Route as publicLayoutRouteImport } from "./routes/(public)/layout";
import { Route as authLayoutRouteImport } from "./routes/(auth)/layout";
import { Route as publicIndexRouteImport } from "./routes/(public)/index";
import { Route as publicUsesRouteImport } from "./routes/(public)/uses";
import { Route as publicStatsRouteImport } from "./routes/(public)/stats";
import { Route as publicProfileRouteImport } from "./routes/(public)/profile";
import { Route as publicGuestbookRouteImport } from "./routes/(public)/guestbook";
import { Route as publicChangelogRouteImport } from "./routes/(public)/changelog";
import { Route as publicAboutRouteImport } from "./routes/(public)/about";
import { Route as authSigninRouteImport } from "./routes/(auth)/signin";
import { Route as ApiContactIndexRouteImport } from "./routes/api/contact/index";
import { Route as ApiChatIndexRouteImport } from "./routes/api/chat/index";
import { Route as ApiChangelogIndexRouteImport } from "./routes/api/changelog/index";
import { Route as publicSnippetsIndexRouteImport } from "./routes/(public)/snippets/index";
import { Route as publicProjectsIndexRouteImport } from "./routes/(public)/projects/index";
import { Route as publicBookmarksIndexRouteImport } from "./routes/(public)/bookmarks/index";
import { Route as publicBlogIndexRouteImport } from "./routes/(public)/blog/index";
import { Route as ApiTrpcSplatRouteImport } from "./routes/api/trpc/$";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as publicSnippetsSnippetIdRouteImport } from "./routes/(public)/snippets/$snippetId";
import { Route as publicServicesServiceIdRouteImport } from "./routes/(public)/services/$serviceId";
import { Route as publicProjectsProjectIdRouteImport } from "./routes/(public)/projects/$projectId";
import { Route as publicBookmarksBookmarkIdRouteImport } from "./routes/(public)/bookmarks/$bookmarkId";
import { Route as publicBlogArticleIdRouteImport } from "./routes/(public)/blog/$articleId";
import { Route as ApiStatsGithubIndexRouteImport } from "./routes/api/stats/github/index";
import { Route as ApiStatsGithubActivityRouteImport } from "./routes/api/stats/github/activity";

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: "/sitemap.xml",
  path: "/sitemap.xml",
  getParentRoute: () => rootRouteImport,
} as any);
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: "/llms.txt",
  path: "/llms.txt",
  getParentRoute: () => rootRouteImport,
} as any);
const publicLayoutRoute = publicLayoutRouteImport.update({
  id: "/(public)",
  getParentRoute: () => rootRouteImport,
} as any);
const authLayoutRoute = authLayoutRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any);
const publicIndexRoute = publicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicUsesRoute = publicUsesRouteImport.update({
  id: "/uses",
  path: "/uses",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicStatsRoute = publicStatsRouteImport.update({
  id: "/stats",
  path: "/stats",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicProfileRoute = publicProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicGuestbookRoute = publicGuestbookRouteImport.update({
  id: "/guestbook",
  path: "/guestbook",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicChangelogRoute = publicChangelogRouteImport.update({
  id: "/changelog",
  path: "/changelog",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicAboutRoute = publicAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => publicLayoutRoute,
} as any);
const authSigninRoute = authSigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => authLayoutRoute,
} as any);
const ApiContactIndexRoute = ApiContactIndexRouteImport.update({
  id: "/api/contact/",
  path: "/api/contact/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: "/api/chat/",
  path: "/api/chat/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiChangelogIndexRoute = ApiChangelogIndexRouteImport.update({
  id: "/api/changelog/",
  path: "/api/changelog/",
  getParentRoute: () => rootRouteImport,
} as any);
const publicSnippetsIndexRoute = publicSnippetsIndexRouteImport.update({
  id: "/snippets/",
  path: "/snippets/",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicProjectsIndexRoute = publicProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicBookmarksIndexRoute = publicBookmarksIndexRouteImport.update({
  id: "/bookmarks/",
  path: "/bookmarks/",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicBlogIndexRoute = publicBlogIndexRouteImport.update({
  id: "/blog/",
  path: "/blog/",
  getParentRoute: () => publicLayoutRoute,
} as any);
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: "/api/trpc/$",
  path: "/api/trpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const publicSnippetsSnippetIdRoute = publicSnippetsSnippetIdRouteImport.update({
  id: "/snippets/$snippetId",
  path: "/snippets/$snippetId",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicServicesServiceIdRoute = publicServicesServiceIdRouteImport.update({
  id: "/services/$serviceId",
  path: "/services/$serviceId",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicProjectsProjectIdRoute = publicProjectsProjectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicBookmarksBookmarkIdRoute =
  publicBookmarksBookmarkIdRouteImport.update({
    id: "/bookmarks/$bookmarkId",
    path: "/bookmarks/$bookmarkId",
    getParentRoute: () => publicLayoutRoute,
  } as any);
const publicBlogArticleIdRoute = publicBlogArticleIdRouteImport.update({
  id: "/blog/$articleId",
  path: "/blog/$articleId",
  getParentRoute: () => publicLayoutRoute,
} as any);
const ApiStatsGithubIndexRoute = ApiStatsGithubIndexRouteImport.update({
  id: "/api/stats/github/",
  path: "/api/stats/github/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiStatsGithubActivityRoute = ApiStatsGithubActivityRouteImport.update({
  id: "/api/stats/github/activity",
  path: "/api/stats/github/activity",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/llms.txt": typeof LlmsDottxtRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/signin": typeof authSigninRoute;
  "/about": typeof publicAboutRoute;
  "/changelog": typeof publicChangelogRoute;
  "/guestbook": typeof publicGuestbookRoute;
  "/profile": typeof publicProfileRoute;
  "/stats": typeof publicStatsRoute;
  "/uses": typeof publicUsesRoute;
  "/": typeof publicIndexRoute;
  "/blog/$articleId": typeof publicBlogArticleIdRoute;
  "/bookmarks/$bookmarkId": typeof publicBookmarksBookmarkIdRoute;
  "/projects/$projectId": typeof publicProjectsProjectIdRoute;
  "/services/$serviceId": typeof publicServicesServiceIdRoute;
  "/snippets/$snippetId": typeof publicSnippetsSnippetIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/trpc/$": typeof ApiTrpcSplatRoute;
  "/blog": typeof publicBlogIndexRoute;
  "/bookmarks": typeof publicBookmarksIndexRoute;
  "/projects": typeof publicProjectsIndexRoute;
  "/snippets": typeof publicSnippetsIndexRoute;
  "/api/changelog": typeof ApiChangelogIndexRoute;
  "/api/chat": typeof ApiChatIndexRoute;
  "/api/contact": typeof ApiContactIndexRoute;
  "/api/stats/github/activity": typeof ApiStatsGithubActivityRoute;
  "/api/stats/github": typeof ApiStatsGithubIndexRoute;
}
export interface FileRoutesByTo {
  "/llms.txt": typeof LlmsDottxtRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/signin": typeof authSigninRoute;
  "/about": typeof publicAboutRoute;
  "/changelog": typeof publicChangelogRoute;
  "/guestbook": typeof publicGuestbookRoute;
  "/profile": typeof publicProfileRoute;
  "/stats": typeof publicStatsRoute;
  "/uses": typeof publicUsesRoute;
  "/": typeof publicIndexRoute;
  "/blog/$articleId": typeof publicBlogArticleIdRoute;
  "/bookmarks/$bookmarkId": typeof publicBookmarksBookmarkIdRoute;
  "/projects/$projectId": typeof publicProjectsProjectIdRoute;
  "/services/$serviceId": typeof publicServicesServiceIdRoute;
  "/snippets/$snippetId": typeof publicSnippetsSnippetIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/trpc/$": typeof ApiTrpcSplatRoute;
  "/blog": typeof publicBlogIndexRoute;
  "/bookmarks": typeof publicBookmarksIndexRoute;
  "/projects": typeof publicProjectsIndexRoute;
  "/snippets": typeof publicSnippetsIndexRoute;
  "/api/changelog": typeof ApiChangelogIndexRoute;
  "/api/chat": typeof ApiChatIndexRoute;
  "/api/contact": typeof ApiContactIndexRoute;
  "/api/stats/github/activity": typeof ApiStatsGithubActivityRoute;
  "/api/stats/github": typeof ApiStatsGithubIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(auth)": typeof authLayoutRouteWithChildren;
  "/(public)": typeof publicLayoutRouteWithChildren;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/(auth)/signin": typeof authSigninRoute;
  "/(public)/about": typeof publicAboutRoute;
  "/(public)/changelog": typeof publicChangelogRoute;
  "/(public)/guestbook": typeof publicGuestbookRoute;
  "/(public)/profile": typeof publicProfileRoute;
  "/(public)/stats": typeof publicStatsRoute;
  "/(public)/uses": typeof publicUsesRoute;
  "/(public)/": typeof publicIndexRoute;
  "/(public)/blog/$articleId": typeof publicBlogArticleIdRoute;
  "/(public)/bookmarks/$bookmarkId": typeof publicBookmarksBookmarkIdRoute;
  "/(public)/projects/$projectId": typeof publicProjectsProjectIdRoute;
  "/(public)/services/$serviceId": typeof publicServicesServiceIdRoute;
  "/(public)/snippets/$snippetId": typeof publicSnippetsSnippetIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/trpc/$": typeof ApiTrpcSplatRoute;
  "/(public)/blog/": typeof publicBlogIndexRoute;
  "/(public)/bookmarks/": typeof publicBookmarksIndexRoute;
  "/(public)/projects/": typeof publicProjectsIndexRoute;
  "/(public)/snippets/": typeof publicSnippetsIndexRoute;
  "/api/changelog/": typeof ApiChangelogIndexRoute;
  "/api/chat/": typeof ApiChatIndexRoute;
  "/api/contact/": typeof ApiContactIndexRoute;
  "/api/stats/github/activity": typeof ApiStatsGithubActivityRoute;
  "/api/stats/github/": typeof ApiStatsGithubIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/llms.txt"
    | "/sitemap.xml"
    | "/signin"
    | "/about"
    | "/changelog"
    | "/guestbook"
    | "/profile"
    | "/stats"
    | "/uses"
    | "/"
    | "/blog/$articleId"
    | "/bookmarks/$bookmarkId"
    | "/projects/$projectId"
    | "/services/$serviceId"
    | "/snippets/$snippetId"
    | "/api/auth/$"
    | "/api/trpc/$"
    | "/blog"
    | "/bookmarks"
    | "/projects"
    | "/snippets"
    | "/api/changelog"
    | "/api/chat"
    | "/api/contact"
    | "/api/stats/github/activity"
    | "/api/stats/github";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/llms.txt"
    | "/sitemap.xml"
    | "/signin"
    | "/about"
    | "/changelog"
    | "/guestbook"
    | "/profile"
    | "/stats"
    | "/uses"
    | "/"
    | "/blog/$articleId"
    | "/bookmarks/$bookmarkId"
    | "/projects/$projectId"
    | "/services/$serviceId"
    | "/snippets/$snippetId"
    | "/api/auth/$"
    | "/api/trpc/$"
    | "/blog"
    | "/bookmarks"
    | "/projects"
    | "/snippets"
    | "/api/changelog"
    | "/api/chat"
    | "/api/contact"
    | "/api/stats/github/activity"
    | "/api/stats/github";
  id:
    | "__root__"
    | "/(auth)"
    | "/(public)"
    | "/llms.txt"
    | "/sitemap.xml"
    | "/(auth)/signin"
    | "/(public)/about"
    | "/(public)/changelog"
    | "/(public)/guestbook"
    | "/(public)/profile"
    | "/(public)/stats"
    | "/(public)/uses"
    | "/(public)/"
    | "/(public)/blog/$articleId"
    | "/(public)/bookmarks/$bookmarkId"
    | "/(public)/projects/$projectId"
    | "/(public)/services/$serviceId"
    | "/(public)/snippets/$snippetId"
    | "/api/auth/$"
    | "/api/trpc/$"
    | "/(public)/blog/"
    | "/(public)/bookmarks/"
    | "/(public)/projects/"
    | "/(public)/snippets/"
    | "/api/changelog/"
    | "/api/chat/"
    | "/api/contact/"
    | "/api/stats/github/activity"
    | "/api/stats/github/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren;
  publicLayoutRoute: typeof publicLayoutRouteWithChildren;
  LlmsDottxtRoute: typeof LlmsDottxtRoute;
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute;
  ApiChangelogIndexRoute: typeof ApiChangelogIndexRoute;
  ApiChatIndexRoute: typeof ApiChatIndexRoute;
  ApiContactIndexRoute: typeof ApiContactIndexRoute;
  ApiStatsGithubActivityRoute: typeof ApiStatsGithubActivityRoute;
  ApiStatsGithubIndexRoute: typeof ApiStatsGithubIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sitemap.xml": {
      id: "/sitemap.xml";
      path: "/sitemap.xml";
      fullPath: "/sitemap.xml";
      preLoaderRoute: typeof SitemapDotxmlRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/llms.txt": {
      id: "/llms.txt";
      path: "/llms.txt";
      fullPath: "/llms.txt";
      preLoaderRoute: typeof LlmsDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(public)": {
      id: "/(public)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof publicLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)": {
      id: "/(auth)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof authLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(public)/": {
      id: "/(public)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof publicIndexRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/uses": {
      id: "/(public)/uses";
      path: "/uses";
      fullPath: "/uses";
      preLoaderRoute: typeof publicUsesRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/stats": {
      id: "/(public)/stats";
      path: "/stats";
      fullPath: "/stats";
      preLoaderRoute: typeof publicStatsRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/profile": {
      id: "/(public)/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof publicProfileRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/guestbook": {
      id: "/(public)/guestbook";
      path: "/guestbook";
      fullPath: "/guestbook";
      preLoaderRoute: typeof publicGuestbookRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/changelog": {
      id: "/(public)/changelog";
      path: "/changelog";
      fullPath: "/changelog";
      preLoaderRoute: typeof publicChangelogRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/about": {
      id: "/(public)/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof publicAboutRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(auth)/signin": {
      id: "/(auth)/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof authSigninRouteImport;
      parentRoute: typeof authLayoutRoute;
    };
    "/api/contact/": {
      id: "/api/contact/";
      path: "/api/contact";
      fullPath: "/api/contact";
      preLoaderRoute: typeof ApiContactIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/chat/": {
      id: "/api/chat/";
      path: "/api/chat";
      fullPath: "/api/chat";
      preLoaderRoute: typeof ApiChatIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/changelog/": {
      id: "/api/changelog/";
      path: "/api/changelog";
      fullPath: "/api/changelog";
      preLoaderRoute: typeof ApiChangelogIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(public)/snippets/": {
      id: "/(public)/snippets/";
      path: "/snippets";
      fullPath: "/snippets";
      preLoaderRoute: typeof publicSnippetsIndexRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/projects/": {
      id: "/(public)/projects/";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof publicProjectsIndexRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/bookmarks/": {
      id: "/(public)/bookmarks/";
      path: "/bookmarks";
      fullPath: "/bookmarks";
      preLoaderRoute: typeof publicBookmarksIndexRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/blog/": {
      id: "/(public)/blog/";
      path: "/blog";
      fullPath: "/blog";
      preLoaderRoute: typeof publicBlogIndexRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/api/trpc/$": {
      id: "/api/trpc/$";
      path: "/api/trpc/$";
      fullPath: "/api/trpc/$";
      preLoaderRoute: typeof ApiTrpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(public)/snippets/$snippetId": {
      id: "/(public)/snippets/$snippetId";
      path: "/snippets/$snippetId";
      fullPath: "/snippets/$snippetId";
      preLoaderRoute: typeof publicSnippetsSnippetIdRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/services/$serviceId": {
      id: "/(public)/services/$serviceId";
      path: "/services/$serviceId";
      fullPath: "/services/$serviceId";
      preLoaderRoute: typeof publicServicesServiceIdRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/projects/$projectId": {
      id: "/(public)/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof publicProjectsProjectIdRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/bookmarks/$bookmarkId": {
      id: "/(public)/bookmarks/$bookmarkId";
      path: "/bookmarks/$bookmarkId";
      fullPath: "/bookmarks/$bookmarkId";
      preLoaderRoute: typeof publicBookmarksBookmarkIdRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/blog/$articleId": {
      id: "/(public)/blog/$articleId";
      path: "/blog/$articleId";
      fullPath: "/blog/$articleId";
      preLoaderRoute: typeof publicBlogArticleIdRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/api/stats/github/": {
      id: "/api/stats/github/";
      path: "/api/stats/github";
      fullPath: "/api/stats/github";
      preLoaderRoute: typeof ApiStatsGithubIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/stats/github/activity": {
      id: "/api/stats/github/activity";
      path: "/api/stats/github/activity";
      fullPath: "/api/stats/github/activity";
      preLoaderRoute: typeof ApiStatsGithubActivityRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface authLayoutRouteChildren {
  authSigninRoute: typeof authSigninRoute;
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authSigninRoute: authSigninRoute,
};

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
);

interface publicLayoutRouteChildren {
  publicAboutRoute: typeof publicAboutRoute;
  publicChangelogRoute: typeof publicChangelogRoute;
  publicGuestbookRoute: typeof publicGuestbookRoute;
  publicProfileRoute: typeof publicProfileRoute;
  publicStatsRoute: typeof publicStatsRoute;
  publicUsesRoute: typeof publicUsesRoute;
  publicIndexRoute: typeof publicIndexRoute;
  publicBlogArticleIdRoute: typeof publicBlogArticleIdRoute;
  publicBookmarksBookmarkIdRoute: typeof publicBookmarksBookmarkIdRoute;
  publicProjectsProjectIdRoute: typeof publicProjectsProjectIdRoute;
  publicServicesServiceIdRoute: typeof publicServicesServiceIdRoute;
  publicSnippetsSnippetIdRoute: typeof publicSnippetsSnippetIdRoute;
  publicBlogIndexRoute: typeof publicBlogIndexRoute;
  publicBookmarksIndexRoute: typeof publicBookmarksIndexRoute;
  publicProjectsIndexRoute: typeof publicProjectsIndexRoute;
  publicSnippetsIndexRoute: typeof publicSnippetsIndexRoute;
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicChangelogRoute: publicChangelogRoute,
  publicGuestbookRoute: publicGuestbookRoute,
  publicProfileRoute: publicProfileRoute,
  publicStatsRoute: publicStatsRoute,
  publicUsesRoute: publicUsesRoute,
  publicIndexRoute: publicIndexRoute,
  publicBlogArticleIdRoute: publicBlogArticleIdRoute,
  publicBookmarksBookmarkIdRoute: publicBookmarksBookmarkIdRoute,
  publicProjectsProjectIdRoute: publicProjectsProjectIdRoute,
  publicServicesServiceIdRoute: publicServicesServiceIdRoute,
  publicSnippetsSnippetIdRoute: publicSnippetsSnippetIdRoute,
  publicBlogIndexRoute: publicBlogIndexRoute,
  publicBookmarksIndexRoute: publicBookmarksIndexRoute,
  publicProjectsIndexRoute: publicProjectsIndexRoute,
  publicSnippetsIndexRoute: publicSnippetsIndexRoute,
};

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  publicLayoutRoute: publicLayoutRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiChangelogIndexRoute: ApiChangelogIndexRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
  ApiContactIndexRoute: ApiContactIndexRoute,
  ApiStatsGithubActivityRoute: ApiStatsGithubActivityRoute,
  ApiStatsGithubIndexRoute: ApiStatsGithubIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
