/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as dashboardLayoutRouteImport } from "./routes/(dashboard)/layout";
import { Route as authLayoutRouteImport } from "./routes/(auth)/layout";
import { Route as dashboardIndexRouteImport } from "./routes/(dashboard)/index";
import { Route as ApiResendRouteImport } from "./routes/api/resend";
import { Route as authSigninRouteImport } from "./routes/(auth)/signin";
import { Route as dashboardUsersIndexRouteImport } from "./routes/(dashboard)/users/index";
import { Route as dashboardSnippetsIndexRouteImport } from "./routes/(dashboard)/snippets/index";
import { Route as dashboardServicesIndexRouteImport } from "./routes/(dashboard)/services/index";
import { Route as dashboardProjectsIndexRouteImport } from "./routes/(dashboard)/projects/index";
import { Route as dashboardExperiencesIndexRouteImport } from "./routes/(dashboard)/experiences/index";
import { Route as dashboardBlogIndexRouteImport } from "./routes/(dashboard)/blog/index";
import { Route as ApiTrpcSplatRouteImport } from "./routes/api/trpc/$";
import { Route as ApiCronProcessCampaignsRouteImport } from "./routes/api/cron/process-campaigns";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as dashboardSnippetsCreateRouteImport } from "./routes/(dashboard)/snippets/create";
import { Route as dashboardServicesCreateRouteImport } from "./routes/(dashboard)/services/create";
import { Route as dashboardProjectsCreateRouteImport } from "./routes/(dashboard)/projects/create";
import { Route as dashboardExperiencesCreateRouteImport } from "./routes/(dashboard)/experiences/create";
import { Route as dashboardBlogCreateRouteImport } from "./routes/(dashboard)/blog/create";
import { Route as ApiAiBlogAssistIndexRouteImport } from "./routes/api/ai/blog-assist/index";
import { Route as dashboardMarketingSocialIndexRouteImport } from "./routes/(dashboard)/marketing/social/index";
import { Route as dashboardMarketingEmailIndexRouteImport } from "./routes/(dashboard)/marketing/email/index";
import { Route as dashboardSnippetsSnippetIdEditRouteImport } from "./routes/(dashboard)/snippets/$snippetId.edit";
import { Route as dashboardServicesServiceIdEditRouteImport } from "./routes/(dashboard)/services/$serviceId.edit";
import { Route as dashboardProjectsProjectIdEditRouteImport } from "./routes/(dashboard)/projects/$projectId.edit";
import { Route as dashboardExperiencesExperienceIdEditRouteImport } from "./routes/(dashboard)/experiences/$experienceId.edit";
import { Route as dashboardBlogArticleIdEditRouteImport } from "./routes/(dashboard)/blog/$articleId.edit";
import { Route as dashboardMarketingEmailSubscribersIndexRouteImport } from "./routes/(dashboard)/marketing/email/subscribers/index";
import { Route as dashboardMarketingSocialPostsCreateRouteImport } from "./routes/(dashboard)/marketing/social/posts/create";
import { Route as dashboardMarketingSocialPostsPostIdRouteImport } from "./routes/(dashboard)/marketing/social/posts/$postId";
import { Route as dashboardMarketingEmailCampaignsCreateRouteImport } from "./routes/(dashboard)/marketing/email/campaigns/create";
import { Route as dashboardMarketingEmailCampaignsCampaignIdRouteImport } from "./routes/(dashboard)/marketing/email/campaigns/$campaignId";
import { Route as dashboardMarketingSocialPostsPostIdEditRouteImport } from "./routes/(dashboard)/marketing/social/posts/$postId/edit";
import { Route as dashboardMarketingEmailCampaignsCampaignIdEditRouteImport } from "./routes/(dashboard)/marketing/email/campaigns/$campaignId/edit";

const dashboardLayoutRoute = dashboardLayoutRouteImport.update({
  id: "/(dashboard)",
  getParentRoute: () => rootRouteImport,
} as any);
const authLayoutRoute = authLayoutRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any);
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const ApiResendRoute = ApiResendRouteImport.update({
  id: "/api/resend",
  path: "/api/resend",
  getParentRoute: () => rootRouteImport,
} as any);
const authSigninRoute = authSigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => authLayoutRoute,
} as any);
const dashboardUsersIndexRoute = dashboardUsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardSnippetsIndexRoute = dashboardSnippetsIndexRouteImport.update({
  id: "/snippets/",
  path: "/snippets/",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardServicesIndexRoute = dashboardServicesIndexRouteImport.update({
  id: "/services/",
  path: "/services/",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardProjectsIndexRoute = dashboardProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardExperiencesIndexRoute =
  dashboardExperiencesIndexRouteImport.update({
    id: "/experiences/",
    path: "/experiences/",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardBlogIndexRoute = dashboardBlogIndexRouteImport.update({
  id: "/blog/",
  path: "/blog/",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: "/api/trpc/$",
  path: "/api/trpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiCronProcessCampaignsRoute = ApiCronProcessCampaignsRouteImport.update({
  id: "/api/cron/process-campaigns",
  path: "/api/cron/process-campaigns",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const dashboardSnippetsCreateRoute = dashboardSnippetsCreateRouteImport.update({
  id: "/snippets/create",
  path: "/snippets/create",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardServicesCreateRoute = dashboardServicesCreateRouteImport.update({
  id: "/services/create",
  path: "/services/create",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardProjectsCreateRoute = dashboardProjectsCreateRouteImport.update({
  id: "/projects/create",
  path: "/projects/create",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const dashboardExperiencesCreateRoute =
  dashboardExperiencesCreateRouteImport.update({
    id: "/experiences/create",
    path: "/experiences/create",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardBlogCreateRoute = dashboardBlogCreateRouteImport.update({
  id: "/blog/create",
  path: "/blog/create",
  getParentRoute: () => dashboardLayoutRoute,
} as any);
const ApiAiBlogAssistIndexRoute = ApiAiBlogAssistIndexRouteImport.update({
  id: "/api/ai/blog-assist/",
  path: "/api/ai/blog-assist/",
  getParentRoute: () => rootRouteImport,
} as any);
const dashboardMarketingSocialIndexRoute =
  dashboardMarketingSocialIndexRouteImport.update({
    id: "/marketing/social/",
    path: "/marketing/social/",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardMarketingEmailIndexRoute =
  dashboardMarketingEmailIndexRouteImport.update({
    id: "/marketing/email/",
    path: "/marketing/email/",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardSnippetsSnippetIdEditRoute =
  dashboardSnippetsSnippetIdEditRouteImport.update({
    id: "/snippets/$snippetId/edit",
    path: "/snippets/$snippetId/edit",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardServicesServiceIdEditRoute =
  dashboardServicesServiceIdEditRouteImport.update({
    id: "/services/$serviceId/edit",
    path: "/services/$serviceId/edit",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardProjectsProjectIdEditRoute =
  dashboardProjectsProjectIdEditRouteImport.update({
    id: "/projects/$projectId/edit",
    path: "/projects/$projectId/edit",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardExperiencesExperienceIdEditRoute =
  dashboardExperiencesExperienceIdEditRouteImport.update({
    id: "/experiences/$experienceId/edit",
    path: "/experiences/$experienceId/edit",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardBlogArticleIdEditRoute =
  dashboardBlogArticleIdEditRouteImport.update({
    id: "/blog/$articleId/edit",
    path: "/blog/$articleId/edit",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardMarketingEmailSubscribersIndexRoute =
  dashboardMarketingEmailSubscribersIndexRouteImport.update({
    id: "/marketing/email/subscribers/",
    path: "/marketing/email/subscribers/",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardMarketingSocialPostsCreateRoute =
  dashboardMarketingSocialPostsCreateRouteImport.update({
    id: "/marketing/social/posts/create",
    path: "/marketing/social/posts/create",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardMarketingSocialPostsPostIdRoute =
  dashboardMarketingSocialPostsPostIdRouteImport.update({
    id: "/marketing/social/posts/$postId",
    path: "/marketing/social/posts/$postId",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardMarketingEmailCampaignsCreateRoute =
  dashboardMarketingEmailCampaignsCreateRouteImport.update({
    id: "/marketing/email/campaigns/create",
    path: "/marketing/email/campaigns/create",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardMarketingEmailCampaignsCampaignIdRoute =
  dashboardMarketingEmailCampaignsCampaignIdRouteImport.update({
    id: "/marketing/email/campaigns/$campaignId",
    path: "/marketing/email/campaigns/$campaignId",
    getParentRoute: () => dashboardLayoutRoute,
  } as any);
const dashboardMarketingSocialPostsPostIdEditRoute =
  dashboardMarketingSocialPostsPostIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => dashboardMarketingSocialPostsPostIdRoute,
  } as any);
const dashboardMarketingEmailCampaignsCampaignIdEditRoute =
  dashboardMarketingEmailCampaignsCampaignIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => dashboardMarketingEmailCampaignsCampaignIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/signin": typeof authSigninRoute;
  "/api/resend": typeof ApiResendRoute;
  "/": typeof dashboardIndexRoute;
  "/blog/create": typeof dashboardBlogCreateRoute;
  "/experiences/create": typeof dashboardExperiencesCreateRoute;
  "/projects/create": typeof dashboardProjectsCreateRoute;
  "/services/create": typeof dashboardServicesCreateRoute;
  "/snippets/create": typeof dashboardSnippetsCreateRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/cron/process-campaigns": typeof ApiCronProcessCampaignsRoute;
  "/api/trpc/$": typeof ApiTrpcSplatRoute;
  "/blog": typeof dashboardBlogIndexRoute;
  "/experiences": typeof dashboardExperiencesIndexRoute;
  "/projects": typeof dashboardProjectsIndexRoute;
  "/services": typeof dashboardServicesIndexRoute;
  "/snippets": typeof dashboardSnippetsIndexRoute;
  "/users": typeof dashboardUsersIndexRoute;
  "/blog/$articleId/edit": typeof dashboardBlogArticleIdEditRoute;
  "/experiences/$experienceId/edit": typeof dashboardExperiencesExperienceIdEditRoute;
  "/projects/$projectId/edit": typeof dashboardProjectsProjectIdEditRoute;
  "/services/$serviceId/edit": typeof dashboardServicesServiceIdEditRoute;
  "/snippets/$snippetId/edit": typeof dashboardSnippetsSnippetIdEditRoute;
  "/marketing/email": typeof dashboardMarketingEmailIndexRoute;
  "/marketing/social": typeof dashboardMarketingSocialIndexRoute;
  "/api/ai/blog-assist": typeof ApiAiBlogAssistIndexRoute;
  "/marketing/email/campaigns/$campaignId": typeof dashboardMarketingEmailCampaignsCampaignIdRouteWithChildren;
  "/marketing/email/campaigns/create": typeof dashboardMarketingEmailCampaignsCreateRoute;
  "/marketing/social/posts/$postId": typeof dashboardMarketingSocialPostsPostIdRouteWithChildren;
  "/marketing/social/posts/create": typeof dashboardMarketingSocialPostsCreateRoute;
  "/marketing/email/subscribers": typeof dashboardMarketingEmailSubscribersIndexRoute;
  "/marketing/email/campaigns/$campaignId/edit": typeof dashboardMarketingEmailCampaignsCampaignIdEditRoute;
  "/marketing/social/posts/$postId/edit": typeof dashboardMarketingSocialPostsPostIdEditRoute;
}
export interface FileRoutesByTo {
  "/signin": typeof authSigninRoute;
  "/api/resend": typeof ApiResendRoute;
  "/": typeof dashboardIndexRoute;
  "/blog/create": typeof dashboardBlogCreateRoute;
  "/experiences/create": typeof dashboardExperiencesCreateRoute;
  "/projects/create": typeof dashboardProjectsCreateRoute;
  "/services/create": typeof dashboardServicesCreateRoute;
  "/snippets/create": typeof dashboardSnippetsCreateRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/cron/process-campaigns": typeof ApiCronProcessCampaignsRoute;
  "/api/trpc/$": typeof ApiTrpcSplatRoute;
  "/blog": typeof dashboardBlogIndexRoute;
  "/experiences": typeof dashboardExperiencesIndexRoute;
  "/projects": typeof dashboardProjectsIndexRoute;
  "/services": typeof dashboardServicesIndexRoute;
  "/snippets": typeof dashboardSnippetsIndexRoute;
  "/users": typeof dashboardUsersIndexRoute;
  "/blog/$articleId/edit": typeof dashboardBlogArticleIdEditRoute;
  "/experiences/$experienceId/edit": typeof dashboardExperiencesExperienceIdEditRoute;
  "/projects/$projectId/edit": typeof dashboardProjectsProjectIdEditRoute;
  "/services/$serviceId/edit": typeof dashboardServicesServiceIdEditRoute;
  "/snippets/$snippetId/edit": typeof dashboardSnippetsSnippetIdEditRoute;
  "/marketing/email": typeof dashboardMarketingEmailIndexRoute;
  "/marketing/social": typeof dashboardMarketingSocialIndexRoute;
  "/api/ai/blog-assist": typeof ApiAiBlogAssistIndexRoute;
  "/marketing/email/campaigns/$campaignId": typeof dashboardMarketingEmailCampaignsCampaignIdRouteWithChildren;
  "/marketing/email/campaigns/create": typeof dashboardMarketingEmailCampaignsCreateRoute;
  "/marketing/social/posts/$postId": typeof dashboardMarketingSocialPostsPostIdRouteWithChildren;
  "/marketing/social/posts/create": typeof dashboardMarketingSocialPostsCreateRoute;
  "/marketing/email/subscribers": typeof dashboardMarketingEmailSubscribersIndexRoute;
  "/marketing/email/campaigns/$campaignId/edit": typeof dashboardMarketingEmailCampaignsCampaignIdEditRoute;
  "/marketing/social/posts/$postId/edit": typeof dashboardMarketingSocialPostsPostIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(auth)": typeof authLayoutRouteWithChildren;
  "/(dashboard)": typeof dashboardLayoutRouteWithChildren;
  "/(auth)/signin": typeof authSigninRoute;
  "/api/resend": typeof ApiResendRoute;
  "/(dashboard)/": typeof dashboardIndexRoute;
  "/(dashboard)/blog/create": typeof dashboardBlogCreateRoute;
  "/(dashboard)/experiences/create": typeof dashboardExperiencesCreateRoute;
  "/(dashboard)/projects/create": typeof dashboardProjectsCreateRoute;
  "/(dashboard)/services/create": typeof dashboardServicesCreateRoute;
  "/(dashboard)/snippets/create": typeof dashboardSnippetsCreateRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/cron/process-campaigns": typeof ApiCronProcessCampaignsRoute;
  "/api/trpc/$": typeof ApiTrpcSplatRoute;
  "/(dashboard)/blog/": typeof dashboardBlogIndexRoute;
  "/(dashboard)/experiences/": typeof dashboardExperiencesIndexRoute;
  "/(dashboard)/projects/": typeof dashboardProjectsIndexRoute;
  "/(dashboard)/services/": typeof dashboardServicesIndexRoute;
  "/(dashboard)/snippets/": typeof dashboardSnippetsIndexRoute;
  "/(dashboard)/users/": typeof dashboardUsersIndexRoute;
  "/(dashboard)/blog/$articleId/edit": typeof dashboardBlogArticleIdEditRoute;
  "/(dashboard)/experiences/$experienceId/edit": typeof dashboardExperiencesExperienceIdEditRoute;
  "/(dashboard)/projects/$projectId/edit": typeof dashboardProjectsProjectIdEditRoute;
  "/(dashboard)/services/$serviceId/edit": typeof dashboardServicesServiceIdEditRoute;
  "/(dashboard)/snippets/$snippetId/edit": typeof dashboardSnippetsSnippetIdEditRoute;
  "/(dashboard)/marketing/email/": typeof dashboardMarketingEmailIndexRoute;
  "/(dashboard)/marketing/social/": typeof dashboardMarketingSocialIndexRoute;
  "/api/ai/blog-assist/": typeof ApiAiBlogAssistIndexRoute;
  "/(dashboard)/marketing/email/campaigns/$campaignId": typeof dashboardMarketingEmailCampaignsCampaignIdRouteWithChildren;
  "/(dashboard)/marketing/email/campaigns/create": typeof dashboardMarketingEmailCampaignsCreateRoute;
  "/(dashboard)/marketing/social/posts/$postId": typeof dashboardMarketingSocialPostsPostIdRouteWithChildren;
  "/(dashboard)/marketing/social/posts/create": typeof dashboardMarketingSocialPostsCreateRoute;
  "/(dashboard)/marketing/email/subscribers/": typeof dashboardMarketingEmailSubscribersIndexRoute;
  "/(dashboard)/marketing/email/campaigns/$campaignId/edit": typeof dashboardMarketingEmailCampaignsCampaignIdEditRoute;
  "/(dashboard)/marketing/social/posts/$postId/edit": typeof dashboardMarketingSocialPostsPostIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/signin"
    | "/api/resend"
    | "/"
    | "/blog/create"
    | "/experiences/create"
    | "/projects/create"
    | "/services/create"
    | "/snippets/create"
    | "/api/auth/$"
    | "/api/cron/process-campaigns"
    | "/api/trpc/$"
    | "/blog"
    | "/experiences"
    | "/projects"
    | "/services"
    | "/snippets"
    | "/users"
    | "/blog/$articleId/edit"
    | "/experiences/$experienceId/edit"
    | "/projects/$projectId/edit"
    | "/services/$serviceId/edit"
    | "/snippets/$snippetId/edit"
    | "/marketing/email"
    | "/marketing/social"
    | "/api/ai/blog-assist"
    | "/marketing/email/campaigns/$campaignId"
    | "/marketing/email/campaigns/create"
    | "/marketing/social/posts/$postId"
    | "/marketing/social/posts/create"
    | "/marketing/email/subscribers"
    | "/marketing/email/campaigns/$campaignId/edit"
    | "/marketing/social/posts/$postId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/signin"
    | "/api/resend"
    | "/"
    | "/blog/create"
    | "/experiences/create"
    | "/projects/create"
    | "/services/create"
    | "/snippets/create"
    | "/api/auth/$"
    | "/api/cron/process-campaigns"
    | "/api/trpc/$"
    | "/blog"
    | "/experiences"
    | "/projects"
    | "/services"
    | "/snippets"
    | "/users"
    | "/blog/$articleId/edit"
    | "/experiences/$experienceId/edit"
    | "/projects/$projectId/edit"
    | "/services/$serviceId/edit"
    | "/snippets/$snippetId/edit"
    | "/marketing/email"
    | "/marketing/social"
    | "/api/ai/blog-assist"
    | "/marketing/email/campaigns/$campaignId"
    | "/marketing/email/campaigns/create"
    | "/marketing/social/posts/$postId"
    | "/marketing/social/posts/create"
    | "/marketing/email/subscribers"
    | "/marketing/email/campaigns/$campaignId/edit"
    | "/marketing/social/posts/$postId/edit";
  id:
    | "__root__"
    | "/(auth)"
    | "/(dashboard)"
    | "/(auth)/signin"
    | "/api/resend"
    | "/(dashboard)/"
    | "/(dashboard)/blog/create"
    | "/(dashboard)/experiences/create"
    | "/(dashboard)/projects/create"
    | "/(dashboard)/services/create"
    | "/(dashboard)/snippets/create"
    | "/api/auth/$"
    | "/api/cron/process-campaigns"
    | "/api/trpc/$"
    | "/(dashboard)/blog/"
    | "/(dashboard)/experiences/"
    | "/(dashboard)/projects/"
    | "/(dashboard)/services/"
    | "/(dashboard)/snippets/"
    | "/(dashboard)/users/"
    | "/(dashboard)/blog/$articleId/edit"
    | "/(dashboard)/experiences/$experienceId/edit"
    | "/(dashboard)/projects/$projectId/edit"
    | "/(dashboard)/services/$serviceId/edit"
    | "/(dashboard)/snippets/$snippetId/edit"
    | "/(dashboard)/marketing/email/"
    | "/(dashboard)/marketing/social/"
    | "/api/ai/blog-assist/"
    | "/(dashboard)/marketing/email/campaigns/$campaignId"
    | "/(dashboard)/marketing/email/campaigns/create"
    | "/(dashboard)/marketing/social/posts/$postId"
    | "/(dashboard)/marketing/social/posts/create"
    | "/(dashboard)/marketing/email/subscribers/"
    | "/(dashboard)/marketing/email/campaigns/$campaignId/edit"
    | "/(dashboard)/marketing/social/posts/$postId/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren;
  dashboardLayoutRoute: typeof dashboardLayoutRouteWithChildren;
  ApiResendRoute: typeof ApiResendRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiCronProcessCampaignsRoute: typeof ApiCronProcessCampaignsRoute;
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute;
  ApiAiBlogAssistIndexRoute: typeof ApiAiBlogAssistIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(dashboard)": {
      id: "/(dashboard)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof dashboardLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)": {
      id: "/(auth)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof authLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(dashboard)/": {
      id: "/(dashboard)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof dashboardIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/api/resend": {
      id: "/api/resend";
      path: "/api/resend";
      fullPath: "/api/resend";
      preLoaderRoute: typeof ApiResendRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/signin": {
      id: "/(auth)/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof authSigninRouteImport;
      parentRoute: typeof authLayoutRoute;
    };
    "/(dashboard)/users/": {
      id: "/(dashboard)/users/";
      path: "/users";
      fullPath: "/users";
      preLoaderRoute: typeof dashboardUsersIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/snippets/": {
      id: "/(dashboard)/snippets/";
      path: "/snippets";
      fullPath: "/snippets";
      preLoaderRoute: typeof dashboardSnippetsIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/services/": {
      id: "/(dashboard)/services/";
      path: "/services";
      fullPath: "/services";
      preLoaderRoute: typeof dashboardServicesIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/projects/": {
      id: "/(dashboard)/projects/";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof dashboardProjectsIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/experiences/": {
      id: "/(dashboard)/experiences/";
      path: "/experiences";
      fullPath: "/experiences";
      preLoaderRoute: typeof dashboardExperiencesIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/blog/": {
      id: "/(dashboard)/blog/";
      path: "/blog";
      fullPath: "/blog";
      preLoaderRoute: typeof dashboardBlogIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/api/trpc/$": {
      id: "/api/trpc/$";
      path: "/api/trpc/$";
      fullPath: "/api/trpc/$";
      preLoaderRoute: typeof ApiTrpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/cron/process-campaigns": {
      id: "/api/cron/process-campaigns";
      path: "/api/cron/process-campaigns";
      fullPath: "/api/cron/process-campaigns";
      preLoaderRoute: typeof ApiCronProcessCampaignsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(dashboard)/snippets/create": {
      id: "/(dashboard)/snippets/create";
      path: "/snippets/create";
      fullPath: "/snippets/create";
      preLoaderRoute: typeof dashboardSnippetsCreateRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/services/create": {
      id: "/(dashboard)/services/create";
      path: "/services/create";
      fullPath: "/services/create";
      preLoaderRoute: typeof dashboardServicesCreateRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/projects/create": {
      id: "/(dashboard)/projects/create";
      path: "/projects/create";
      fullPath: "/projects/create";
      preLoaderRoute: typeof dashboardProjectsCreateRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/experiences/create": {
      id: "/(dashboard)/experiences/create";
      path: "/experiences/create";
      fullPath: "/experiences/create";
      preLoaderRoute: typeof dashboardExperiencesCreateRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/blog/create": {
      id: "/(dashboard)/blog/create";
      path: "/blog/create";
      fullPath: "/blog/create";
      preLoaderRoute: typeof dashboardBlogCreateRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/api/ai/blog-assist/": {
      id: "/api/ai/blog-assist/";
      path: "/api/ai/blog-assist";
      fullPath: "/api/ai/blog-assist";
      preLoaderRoute: typeof ApiAiBlogAssistIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(dashboard)/marketing/social/": {
      id: "/(dashboard)/marketing/social/";
      path: "/marketing/social";
      fullPath: "/marketing/social";
      preLoaderRoute: typeof dashboardMarketingSocialIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/marketing/email/": {
      id: "/(dashboard)/marketing/email/";
      path: "/marketing/email";
      fullPath: "/marketing/email";
      preLoaderRoute: typeof dashboardMarketingEmailIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/snippets/$snippetId/edit": {
      id: "/(dashboard)/snippets/$snippetId/edit";
      path: "/snippets/$snippetId/edit";
      fullPath: "/snippets/$snippetId/edit";
      preLoaderRoute: typeof dashboardSnippetsSnippetIdEditRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/services/$serviceId/edit": {
      id: "/(dashboard)/services/$serviceId/edit";
      path: "/services/$serviceId/edit";
      fullPath: "/services/$serviceId/edit";
      preLoaderRoute: typeof dashboardServicesServiceIdEditRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/projects/$projectId/edit": {
      id: "/(dashboard)/projects/$projectId/edit";
      path: "/projects/$projectId/edit";
      fullPath: "/projects/$projectId/edit";
      preLoaderRoute: typeof dashboardProjectsProjectIdEditRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/experiences/$experienceId/edit": {
      id: "/(dashboard)/experiences/$experienceId/edit";
      path: "/experiences/$experienceId/edit";
      fullPath: "/experiences/$experienceId/edit";
      preLoaderRoute: typeof dashboardExperiencesExperienceIdEditRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/blog/$articleId/edit": {
      id: "/(dashboard)/blog/$articleId/edit";
      path: "/blog/$articleId/edit";
      fullPath: "/blog/$articleId/edit";
      preLoaderRoute: typeof dashboardBlogArticleIdEditRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/marketing/email/subscribers/": {
      id: "/(dashboard)/marketing/email/subscribers/";
      path: "/marketing/email/subscribers";
      fullPath: "/marketing/email/subscribers";
      preLoaderRoute: typeof dashboardMarketingEmailSubscribersIndexRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/marketing/social/posts/create": {
      id: "/(dashboard)/marketing/social/posts/create";
      path: "/marketing/social/posts/create";
      fullPath: "/marketing/social/posts/create";
      preLoaderRoute: typeof dashboardMarketingSocialPostsCreateRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/marketing/social/posts/$postId": {
      id: "/(dashboard)/marketing/social/posts/$postId";
      path: "/marketing/social/posts/$postId";
      fullPath: "/marketing/social/posts/$postId";
      preLoaderRoute: typeof dashboardMarketingSocialPostsPostIdRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/marketing/email/campaigns/create": {
      id: "/(dashboard)/marketing/email/campaigns/create";
      path: "/marketing/email/campaigns/create";
      fullPath: "/marketing/email/campaigns/create";
      preLoaderRoute: typeof dashboardMarketingEmailCampaignsCreateRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/marketing/email/campaigns/$campaignId": {
      id: "/(dashboard)/marketing/email/campaigns/$campaignId";
      path: "/marketing/email/campaigns/$campaignId";
      fullPath: "/marketing/email/campaigns/$campaignId";
      preLoaderRoute: typeof dashboardMarketingEmailCampaignsCampaignIdRouteImport;
      parentRoute: typeof dashboardLayoutRoute;
    };
    "/(dashboard)/marketing/social/posts/$postId/edit": {
      id: "/(dashboard)/marketing/social/posts/$postId/edit";
      path: "/edit";
      fullPath: "/marketing/social/posts/$postId/edit";
      preLoaderRoute: typeof dashboardMarketingSocialPostsPostIdEditRouteImport;
      parentRoute: typeof dashboardMarketingSocialPostsPostIdRoute;
    };
    "/(dashboard)/marketing/email/campaigns/$campaignId/edit": {
      id: "/(dashboard)/marketing/email/campaigns/$campaignId/edit";
      path: "/edit";
      fullPath: "/marketing/email/campaigns/$campaignId/edit";
      preLoaderRoute: typeof dashboardMarketingEmailCampaignsCampaignIdEditRouteImport;
      parentRoute: typeof dashboardMarketingEmailCampaignsCampaignIdRoute;
    };
  }
}

interface authLayoutRouteChildren {
  authSigninRoute: typeof authSigninRoute;
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authSigninRoute: authSigninRoute,
};

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
);

interface dashboardMarketingEmailCampaignsCampaignIdRouteChildren {
  dashboardMarketingEmailCampaignsCampaignIdEditRoute: typeof dashboardMarketingEmailCampaignsCampaignIdEditRoute;
}

const dashboardMarketingEmailCampaignsCampaignIdRouteChildren: dashboardMarketingEmailCampaignsCampaignIdRouteChildren =
  {
    dashboardMarketingEmailCampaignsCampaignIdEditRoute:
      dashboardMarketingEmailCampaignsCampaignIdEditRoute,
  };

const dashboardMarketingEmailCampaignsCampaignIdRouteWithChildren =
  dashboardMarketingEmailCampaignsCampaignIdRoute._addFileChildren(
    dashboardMarketingEmailCampaignsCampaignIdRouteChildren,
  );

interface dashboardMarketingSocialPostsPostIdRouteChildren {
  dashboardMarketingSocialPostsPostIdEditRoute: typeof dashboardMarketingSocialPostsPostIdEditRoute;
}

const dashboardMarketingSocialPostsPostIdRouteChildren: dashboardMarketingSocialPostsPostIdRouteChildren =
  {
    dashboardMarketingSocialPostsPostIdEditRoute:
      dashboardMarketingSocialPostsPostIdEditRoute,
  };

const dashboardMarketingSocialPostsPostIdRouteWithChildren =
  dashboardMarketingSocialPostsPostIdRoute._addFileChildren(
    dashboardMarketingSocialPostsPostIdRouteChildren,
  );

interface dashboardLayoutRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute;
  dashboardBlogCreateRoute: typeof dashboardBlogCreateRoute;
  dashboardExperiencesCreateRoute: typeof dashboardExperiencesCreateRoute;
  dashboardProjectsCreateRoute: typeof dashboardProjectsCreateRoute;
  dashboardServicesCreateRoute: typeof dashboardServicesCreateRoute;
  dashboardSnippetsCreateRoute: typeof dashboardSnippetsCreateRoute;
  dashboardBlogIndexRoute: typeof dashboardBlogIndexRoute;
  dashboardExperiencesIndexRoute: typeof dashboardExperiencesIndexRoute;
  dashboardProjectsIndexRoute: typeof dashboardProjectsIndexRoute;
  dashboardServicesIndexRoute: typeof dashboardServicesIndexRoute;
  dashboardSnippetsIndexRoute: typeof dashboardSnippetsIndexRoute;
  dashboardUsersIndexRoute: typeof dashboardUsersIndexRoute;
  dashboardBlogArticleIdEditRoute: typeof dashboardBlogArticleIdEditRoute;
  dashboardExperiencesExperienceIdEditRoute: typeof dashboardExperiencesExperienceIdEditRoute;
  dashboardProjectsProjectIdEditRoute: typeof dashboardProjectsProjectIdEditRoute;
  dashboardServicesServiceIdEditRoute: typeof dashboardServicesServiceIdEditRoute;
  dashboardSnippetsSnippetIdEditRoute: typeof dashboardSnippetsSnippetIdEditRoute;
  dashboardMarketingEmailIndexRoute: typeof dashboardMarketingEmailIndexRoute;
  dashboardMarketingSocialIndexRoute: typeof dashboardMarketingSocialIndexRoute;
  dashboardMarketingEmailCampaignsCampaignIdRoute: typeof dashboardMarketingEmailCampaignsCampaignIdRouteWithChildren;
  dashboardMarketingEmailCampaignsCreateRoute: typeof dashboardMarketingEmailCampaignsCreateRoute;
  dashboardMarketingSocialPostsPostIdRoute: typeof dashboardMarketingSocialPostsPostIdRouteWithChildren;
  dashboardMarketingSocialPostsCreateRoute: typeof dashboardMarketingSocialPostsCreateRoute;
  dashboardMarketingEmailSubscribersIndexRoute: typeof dashboardMarketingEmailSubscribersIndexRoute;
}

const dashboardLayoutRouteChildren: dashboardLayoutRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardBlogCreateRoute: dashboardBlogCreateRoute,
  dashboardExperiencesCreateRoute: dashboardExperiencesCreateRoute,
  dashboardProjectsCreateRoute: dashboardProjectsCreateRoute,
  dashboardServicesCreateRoute: dashboardServicesCreateRoute,
  dashboardSnippetsCreateRoute: dashboardSnippetsCreateRoute,
  dashboardBlogIndexRoute: dashboardBlogIndexRoute,
  dashboardExperiencesIndexRoute: dashboardExperiencesIndexRoute,
  dashboardProjectsIndexRoute: dashboardProjectsIndexRoute,
  dashboardServicesIndexRoute: dashboardServicesIndexRoute,
  dashboardSnippetsIndexRoute: dashboardSnippetsIndexRoute,
  dashboardUsersIndexRoute: dashboardUsersIndexRoute,
  dashboardBlogArticleIdEditRoute: dashboardBlogArticleIdEditRoute,
  dashboardExperiencesExperienceIdEditRoute:
    dashboardExperiencesExperienceIdEditRoute,
  dashboardProjectsProjectIdEditRoute: dashboardProjectsProjectIdEditRoute,
  dashboardServicesServiceIdEditRoute: dashboardServicesServiceIdEditRoute,
  dashboardSnippetsSnippetIdEditRoute: dashboardSnippetsSnippetIdEditRoute,
  dashboardMarketingEmailIndexRoute: dashboardMarketingEmailIndexRoute,
  dashboardMarketingSocialIndexRoute: dashboardMarketingSocialIndexRoute,
  dashboardMarketingEmailCampaignsCampaignIdRoute:
    dashboardMarketingEmailCampaignsCampaignIdRouteWithChildren,
  dashboardMarketingEmailCampaignsCreateRoute:
    dashboardMarketingEmailCampaignsCreateRoute,
  dashboardMarketingSocialPostsPostIdRoute:
    dashboardMarketingSocialPostsPostIdRouteWithChildren,
  dashboardMarketingSocialPostsCreateRoute:
    dashboardMarketingSocialPostsCreateRoute,
  dashboardMarketingEmailSubscribersIndexRoute:
    dashboardMarketingEmailSubscribersIndexRoute,
};

const dashboardLayoutRouteWithChildren = dashboardLayoutRoute._addFileChildren(
  dashboardLayoutRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  dashboardLayoutRoute: dashboardLayoutRouteWithChildren,
  ApiResendRoute: ApiResendRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronProcessCampaignsRoute: ApiCronProcessCampaignsRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiAiBlogAssistIndexRoute: ApiAiBlogAssistIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
