/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DefaultLayoutRouteImport } from "./routes/_defaultLayout";
import { Route as DashboardLayoutRouteImport } from "./routes/_dashboardLayout";
import { Route as AuthLayoutRouteImport } from "./routes/_authLayout";
import { Route as DefaultLayoutIndexRouteImport } from "./routes/_defaultLayout/index";
import { Route as DefaultLayoutUsesRouteImport } from "./routes/_defaultLayout/uses";
import { Route as DefaultLayoutStatsRouteImport } from "./routes/_defaultLayout/stats";
import { Route as DefaultLayoutProfileRouteImport } from "./routes/_defaultLayout/profile";
import { Route as DefaultLayoutAboutRouteImport } from "./routes/_defaultLayout/about";
import { Route as AuthLayoutSigninRouteImport } from "./routes/_authLayout/signin";
import { Route as DefaultLayoutSnippetsIndexRouteImport } from "./routes/_defaultLayout/snippets.index";
import { Route as DefaultLayoutProjectsIndexRouteImport } from "./routes/_defaultLayout/projects.index";
import { Route as DefaultLayoutBookmarksIndexRouteImport } from "./routes/_defaultLayout/bookmarks.index";
import { Route as DefaultLayoutBlogIndexRouteImport } from "./routes/_defaultLayout/blog.index";
import { Route as DashboardLayoutDashboardIndexRouteImport } from "./routes/_dashboardLayout/dashboard/index";
import { Route as DefaultLayoutSnippetsSnippetIdRouteImport } from "./routes/_defaultLayout/snippets.$snippetId";
import { Route as DefaultLayoutProjectsProjectIdRouteImport } from "./routes/_defaultLayout/projects.$projectId";
import { Route as DefaultLayoutBookmarksBookmarkIdRouteImport } from "./routes/_defaultLayout/bookmarks.$bookmarkId";
import { Route as DefaultLayoutBlogArticleIdRouteImport } from "./routes/_defaultLayout/blog.$articleId";
import { Route as DashboardLayoutDashboardUsersIndexRouteImport } from "./routes/_dashboardLayout/dashboard/users/index";
import { Route as DashboardLayoutDashboardSnippetsIndexRouteImport } from "./routes/_dashboardLayout/dashboard/snippets/index";
import { Route as DashboardLayoutDashboardProjectsIndexRouteImport } from "./routes/_dashboardLayout/dashboard/projects/index";
import { Route as DashboardLayoutDashboardExperiencesIndexRouteImport } from "./routes/_dashboardLayout/dashboard/experiences/index";
import { Route as DashboardLayoutDashboardBlogIndexRouteImport } from "./routes/_dashboardLayout/dashboard/blog/index";
import { Route as DashboardLayoutDashboardSnippetsCreateRouteImport } from "./routes/_dashboardLayout/dashboard/snippets/create";
import { Route as DashboardLayoutDashboardProjectsCreateRouteImport } from "./routes/_dashboardLayout/dashboard/projects/create";
import { Route as DashboardLayoutDashboardExperiencesCreateRouteImport } from "./routes/_dashboardLayout/dashboard/experiences/create";
import { Route as DashboardLayoutDashboardBlogCreateRouteImport } from "./routes/_dashboardLayout/dashboard/blog/create";
import { Route as DashboardLayoutDashboardSnippetsSnippetIdEditRouteImport } from "./routes/_dashboardLayout/dashboard/snippets/$snippetId.edit";
import { Route as DashboardLayoutDashboardProjectsProjectIdEditRouteImport } from "./routes/_dashboardLayout/dashboard/projects/$projectId.edit";
import { Route as DashboardLayoutDashboardExperiencesExperienceIdEditRouteImport } from "./routes/_dashboardLayout/dashboard/experiences/$experienceId.edit";
import { Route as DashboardLayoutDashboardBlogArticleIdEditRouteImport } from "./routes/_dashboardLayout/dashboard/blog/$articleId.edit";
import { ServerRoute as ApiContactIndexServerRouteImport } from "./routes/api/contact/index";
import { ServerRoute as ApiTrpcSplatServerRouteImport } from "./routes/api/trpc/$";
import { ServerRoute as ApiAuthSplatServerRouteImport } from "./routes/api/auth/$";
import { ServerRoute as ApiStatsGithubIndexServerRouteImport } from "./routes/api/stats/github/index";
import { ServerRoute as ApiStatsGithubActivityServerRouteImport } from "./routes/api/stats/github/activity";

const rootServerRouteImport = createServerRootRoute();

const DefaultLayoutRoute = DefaultLayoutRouteImport.update({
  id: "/_defaultLayout",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: "/_dashboardLayout",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: "/_authLayout",
  getParentRoute: () => rootRouteImport,
} as any);
const DefaultLayoutIndexRoute = DefaultLayoutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DefaultLayoutRoute,
} as any);
const DefaultLayoutUsesRoute = DefaultLayoutUsesRouteImport.update({
  id: "/uses",
  path: "/uses",
  getParentRoute: () => DefaultLayoutRoute,
} as any);
const DefaultLayoutStatsRoute = DefaultLayoutStatsRouteImport.update({
  id: "/stats",
  path: "/stats",
  getParentRoute: () => DefaultLayoutRoute,
} as any);
const DefaultLayoutProfileRoute = DefaultLayoutProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => DefaultLayoutRoute,
} as any);
const DefaultLayoutAboutRoute = DefaultLayoutAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => DefaultLayoutRoute,
} as any);
const AuthLayoutSigninRoute = AuthLayoutSigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => AuthLayoutRoute,
} as any);
const DefaultLayoutSnippetsIndexRoute =
  DefaultLayoutSnippetsIndexRouteImport.update({
    id: "/snippets/",
    path: "/snippets/",
    getParentRoute: () => DefaultLayoutRoute,
  } as any);
const DefaultLayoutProjectsIndexRoute =
  DefaultLayoutProjectsIndexRouteImport.update({
    id: "/projects/",
    path: "/projects/",
    getParentRoute: () => DefaultLayoutRoute,
  } as any);
const DefaultLayoutBookmarksIndexRoute =
  DefaultLayoutBookmarksIndexRouteImport.update({
    id: "/bookmarks/",
    path: "/bookmarks/",
    getParentRoute: () => DefaultLayoutRoute,
  } as any);
const DefaultLayoutBlogIndexRoute = DefaultLayoutBlogIndexRouteImport.update({
  id: "/blog/",
  path: "/blog/",
  getParentRoute: () => DefaultLayoutRoute,
} as any);
const DashboardLayoutDashboardIndexRoute =
  DashboardLayoutDashboardIndexRouteImport.update({
    id: "/dashboard/",
    path: "/dashboard/",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DefaultLayoutSnippetsSnippetIdRoute =
  DefaultLayoutSnippetsSnippetIdRouteImport.update({
    id: "/snippets/$snippetId",
    path: "/snippets/$snippetId",
    getParentRoute: () => DefaultLayoutRoute,
  } as any);
const DefaultLayoutProjectsProjectIdRoute =
  DefaultLayoutProjectsProjectIdRouteImport.update({
    id: "/projects/$projectId",
    path: "/projects/$projectId",
    getParentRoute: () => DefaultLayoutRoute,
  } as any);
const DefaultLayoutBookmarksBookmarkIdRoute =
  DefaultLayoutBookmarksBookmarkIdRouteImport.update({
    id: "/bookmarks/$bookmarkId",
    path: "/bookmarks/$bookmarkId",
    getParentRoute: () => DefaultLayoutRoute,
  } as any);
const DefaultLayoutBlogArticleIdRoute =
  DefaultLayoutBlogArticleIdRouteImport.update({
    id: "/blog/$articleId",
    path: "/blog/$articleId",
    getParentRoute: () => DefaultLayoutRoute,
  } as any);
const DashboardLayoutDashboardUsersIndexRoute =
  DashboardLayoutDashboardUsersIndexRouteImport.update({
    id: "/dashboard/users/",
    path: "/dashboard/users/",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardLayoutDashboardSnippetsIndexRoute =
  DashboardLayoutDashboardSnippetsIndexRouteImport.update({
    id: "/dashboard/snippets/",
    path: "/dashboard/snippets/",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardLayoutDashboardProjectsIndexRoute =
  DashboardLayoutDashboardProjectsIndexRouteImport.update({
    id: "/dashboard/projects/",
    path: "/dashboard/projects/",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardLayoutDashboardExperiencesIndexRoute =
  DashboardLayoutDashboardExperiencesIndexRouteImport.update({
    id: "/dashboard/experiences/",
    path: "/dashboard/experiences/",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardLayoutDashboardBlogIndexRoute =
  DashboardLayoutDashboardBlogIndexRouteImport.update({
    id: "/dashboard/blog/",
    path: "/dashboard/blog/",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardLayoutDashboardSnippetsCreateRoute =
  DashboardLayoutDashboardSnippetsCreateRouteImport.update({
    id: "/dashboard/snippets/create",
    path: "/dashboard/snippets/create",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardLayoutDashboardProjectsCreateRoute =
  DashboardLayoutDashboardProjectsCreateRouteImport.update({
    id: "/dashboard/projects/create",
    path: "/dashboard/projects/create",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardLayoutDashboardExperiencesCreateRoute =
  DashboardLayoutDashboardExperiencesCreateRouteImport.update({
    id: "/dashboard/experiences/create",
    path: "/dashboard/experiences/create",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardLayoutDashboardBlogCreateRoute =
  DashboardLayoutDashboardBlogCreateRouteImport.update({
    id: "/dashboard/blog/create",
    path: "/dashboard/blog/create",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardLayoutDashboardSnippetsSnippetIdEditRoute =
  DashboardLayoutDashboardSnippetsSnippetIdEditRouteImport.update({
    id: "/dashboard/snippets/$snippetId/edit",
    path: "/dashboard/snippets/$snippetId/edit",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardLayoutDashboardProjectsProjectIdEditRoute =
  DashboardLayoutDashboardProjectsProjectIdEditRouteImport.update({
    id: "/dashboard/projects/$projectId/edit",
    path: "/dashboard/projects/$projectId/edit",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardLayoutDashboardExperiencesExperienceIdEditRoute =
  DashboardLayoutDashboardExperiencesExperienceIdEditRouteImport.update({
    id: "/dashboard/experiences/$experienceId/edit",
    path: "/dashboard/experiences/$experienceId/edit",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardLayoutDashboardBlogArticleIdEditRoute =
  DashboardLayoutDashboardBlogArticleIdEditRouteImport.update({
    id: "/dashboard/blog/$articleId/edit",
    path: "/dashboard/blog/$articleId/edit",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const ApiContactIndexServerRoute = ApiContactIndexServerRouteImport.update({
  id: "/api/contact/",
  path: "/api/contact/",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiTrpcSplatServerRoute = ApiTrpcSplatServerRouteImport.update({
  id: "/api/trpc/$",
  path: "/api/trpc/$",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiStatsGithubIndexServerRoute =
  ApiStatsGithubIndexServerRouteImport.update({
    id: "/api/stats/github/",
    path: "/api/stats/github/",
    getParentRoute: () => rootServerRouteImport,
  } as any);
const ApiStatsGithubActivityServerRoute =
  ApiStatsGithubActivityServerRouteImport.update({
    id: "/api/stats/github/activity",
    path: "/api/stats/github/activity",
    getParentRoute: () => rootServerRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/signin": typeof AuthLayoutSigninRoute;
  "/about": typeof DefaultLayoutAboutRoute;
  "/profile": typeof DefaultLayoutProfileRoute;
  "/stats": typeof DefaultLayoutStatsRoute;
  "/uses": typeof DefaultLayoutUsesRoute;
  "/": typeof DefaultLayoutIndexRoute;
  "/blog/$articleId": typeof DefaultLayoutBlogArticleIdRoute;
  "/bookmarks/$bookmarkId": typeof DefaultLayoutBookmarksBookmarkIdRoute;
  "/projects/$projectId": typeof DefaultLayoutProjectsProjectIdRoute;
  "/snippets/$snippetId": typeof DefaultLayoutSnippetsSnippetIdRoute;
  "/dashboard": typeof DashboardLayoutDashboardIndexRoute;
  "/blog": typeof DefaultLayoutBlogIndexRoute;
  "/bookmarks": typeof DefaultLayoutBookmarksIndexRoute;
  "/projects": typeof DefaultLayoutProjectsIndexRoute;
  "/snippets": typeof DefaultLayoutSnippetsIndexRoute;
  "/dashboard/blog/create": typeof DashboardLayoutDashboardBlogCreateRoute;
  "/dashboard/experiences/create": typeof DashboardLayoutDashboardExperiencesCreateRoute;
  "/dashboard/projects/create": typeof DashboardLayoutDashboardProjectsCreateRoute;
  "/dashboard/snippets/create": typeof DashboardLayoutDashboardSnippetsCreateRoute;
  "/dashboard/blog": typeof DashboardLayoutDashboardBlogIndexRoute;
  "/dashboard/experiences": typeof DashboardLayoutDashboardExperiencesIndexRoute;
  "/dashboard/projects": typeof DashboardLayoutDashboardProjectsIndexRoute;
  "/dashboard/snippets": typeof DashboardLayoutDashboardSnippetsIndexRoute;
  "/dashboard/users": typeof DashboardLayoutDashboardUsersIndexRoute;
  "/dashboard/blog/$articleId/edit": typeof DashboardLayoutDashboardBlogArticleIdEditRoute;
  "/dashboard/experiences/$experienceId/edit": typeof DashboardLayoutDashboardExperiencesExperienceIdEditRoute;
  "/dashboard/projects/$projectId/edit": typeof DashboardLayoutDashboardProjectsProjectIdEditRoute;
  "/dashboard/snippets/$snippetId/edit": typeof DashboardLayoutDashboardSnippetsSnippetIdEditRoute;
}
export interface FileRoutesByTo {
  "/signin": typeof AuthLayoutSigninRoute;
  "/about": typeof DefaultLayoutAboutRoute;
  "/profile": typeof DefaultLayoutProfileRoute;
  "/stats": typeof DefaultLayoutStatsRoute;
  "/uses": typeof DefaultLayoutUsesRoute;
  "/": typeof DefaultLayoutIndexRoute;
  "/blog/$articleId": typeof DefaultLayoutBlogArticleIdRoute;
  "/bookmarks/$bookmarkId": typeof DefaultLayoutBookmarksBookmarkIdRoute;
  "/projects/$projectId": typeof DefaultLayoutProjectsProjectIdRoute;
  "/snippets/$snippetId": typeof DefaultLayoutSnippetsSnippetIdRoute;
  "/dashboard": typeof DashboardLayoutDashboardIndexRoute;
  "/blog": typeof DefaultLayoutBlogIndexRoute;
  "/bookmarks": typeof DefaultLayoutBookmarksIndexRoute;
  "/projects": typeof DefaultLayoutProjectsIndexRoute;
  "/snippets": typeof DefaultLayoutSnippetsIndexRoute;
  "/dashboard/blog/create": typeof DashboardLayoutDashboardBlogCreateRoute;
  "/dashboard/experiences/create": typeof DashboardLayoutDashboardExperiencesCreateRoute;
  "/dashboard/projects/create": typeof DashboardLayoutDashboardProjectsCreateRoute;
  "/dashboard/snippets/create": typeof DashboardLayoutDashboardSnippetsCreateRoute;
  "/dashboard/blog": typeof DashboardLayoutDashboardBlogIndexRoute;
  "/dashboard/experiences": typeof DashboardLayoutDashboardExperiencesIndexRoute;
  "/dashboard/projects": typeof DashboardLayoutDashboardProjectsIndexRoute;
  "/dashboard/snippets": typeof DashboardLayoutDashboardSnippetsIndexRoute;
  "/dashboard/users": typeof DashboardLayoutDashboardUsersIndexRoute;
  "/dashboard/blog/$articleId/edit": typeof DashboardLayoutDashboardBlogArticleIdEditRoute;
  "/dashboard/experiences/$experienceId/edit": typeof DashboardLayoutDashboardExperiencesExperienceIdEditRoute;
  "/dashboard/projects/$projectId/edit": typeof DashboardLayoutDashboardProjectsProjectIdEditRoute;
  "/dashboard/snippets/$snippetId/edit": typeof DashboardLayoutDashboardSnippetsSnippetIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_authLayout": typeof AuthLayoutRouteWithChildren;
  "/_dashboardLayout": typeof DashboardLayoutRouteWithChildren;
  "/_defaultLayout": typeof DefaultLayoutRouteWithChildren;
  "/_authLayout/signin": typeof AuthLayoutSigninRoute;
  "/_defaultLayout/about": typeof DefaultLayoutAboutRoute;
  "/_defaultLayout/profile": typeof DefaultLayoutProfileRoute;
  "/_defaultLayout/stats": typeof DefaultLayoutStatsRoute;
  "/_defaultLayout/uses": typeof DefaultLayoutUsesRoute;
  "/_defaultLayout/": typeof DefaultLayoutIndexRoute;
  "/_defaultLayout/blog/$articleId": typeof DefaultLayoutBlogArticleIdRoute;
  "/_defaultLayout/bookmarks/$bookmarkId": typeof DefaultLayoutBookmarksBookmarkIdRoute;
  "/_defaultLayout/projects/$projectId": typeof DefaultLayoutProjectsProjectIdRoute;
  "/_defaultLayout/snippets/$snippetId": typeof DefaultLayoutSnippetsSnippetIdRoute;
  "/_dashboardLayout/dashboard/": typeof DashboardLayoutDashboardIndexRoute;
  "/_defaultLayout/blog/": typeof DefaultLayoutBlogIndexRoute;
  "/_defaultLayout/bookmarks/": typeof DefaultLayoutBookmarksIndexRoute;
  "/_defaultLayout/projects/": typeof DefaultLayoutProjectsIndexRoute;
  "/_defaultLayout/snippets/": typeof DefaultLayoutSnippetsIndexRoute;
  "/_dashboardLayout/dashboard/blog/create": typeof DashboardLayoutDashboardBlogCreateRoute;
  "/_dashboardLayout/dashboard/experiences/create": typeof DashboardLayoutDashboardExperiencesCreateRoute;
  "/_dashboardLayout/dashboard/projects/create": typeof DashboardLayoutDashboardProjectsCreateRoute;
  "/_dashboardLayout/dashboard/snippets/create": typeof DashboardLayoutDashboardSnippetsCreateRoute;
  "/_dashboardLayout/dashboard/blog/": typeof DashboardLayoutDashboardBlogIndexRoute;
  "/_dashboardLayout/dashboard/experiences/": typeof DashboardLayoutDashboardExperiencesIndexRoute;
  "/_dashboardLayout/dashboard/projects/": typeof DashboardLayoutDashboardProjectsIndexRoute;
  "/_dashboardLayout/dashboard/snippets/": typeof DashboardLayoutDashboardSnippetsIndexRoute;
  "/_dashboardLayout/dashboard/users/": typeof DashboardLayoutDashboardUsersIndexRoute;
  "/_dashboardLayout/dashboard/blog/$articleId/edit": typeof DashboardLayoutDashboardBlogArticleIdEditRoute;
  "/_dashboardLayout/dashboard/experiences/$experienceId/edit": typeof DashboardLayoutDashboardExperiencesExperienceIdEditRoute;
  "/_dashboardLayout/dashboard/projects/$projectId/edit": typeof DashboardLayoutDashboardProjectsProjectIdEditRoute;
  "/_dashboardLayout/dashboard/snippets/$snippetId/edit": typeof DashboardLayoutDashboardSnippetsSnippetIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/signin"
    | "/about"
    | "/profile"
    | "/stats"
    | "/uses"
    | "/"
    | "/blog/$articleId"
    | "/bookmarks/$bookmarkId"
    | "/projects/$projectId"
    | "/snippets/$snippetId"
    | "/dashboard"
    | "/blog"
    | "/bookmarks"
    | "/projects"
    | "/snippets"
    | "/dashboard/blog/create"
    | "/dashboard/experiences/create"
    | "/dashboard/projects/create"
    | "/dashboard/snippets/create"
    | "/dashboard/blog"
    | "/dashboard/experiences"
    | "/dashboard/projects"
    | "/dashboard/snippets"
    | "/dashboard/users"
    | "/dashboard/blog/$articleId/edit"
    | "/dashboard/experiences/$experienceId/edit"
    | "/dashboard/projects/$projectId/edit"
    | "/dashboard/snippets/$snippetId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/signin"
    | "/about"
    | "/profile"
    | "/stats"
    | "/uses"
    | "/"
    | "/blog/$articleId"
    | "/bookmarks/$bookmarkId"
    | "/projects/$projectId"
    | "/snippets/$snippetId"
    | "/dashboard"
    | "/blog"
    | "/bookmarks"
    | "/projects"
    | "/snippets"
    | "/dashboard/blog/create"
    | "/dashboard/experiences/create"
    | "/dashboard/projects/create"
    | "/dashboard/snippets/create"
    | "/dashboard/blog"
    | "/dashboard/experiences"
    | "/dashboard/projects"
    | "/dashboard/snippets"
    | "/dashboard/users"
    | "/dashboard/blog/$articleId/edit"
    | "/dashboard/experiences/$experienceId/edit"
    | "/dashboard/projects/$projectId/edit"
    | "/dashboard/snippets/$snippetId/edit";
  id:
    | "__root__"
    | "/_authLayout"
    | "/_dashboardLayout"
    | "/_defaultLayout"
    | "/_authLayout/signin"
    | "/_defaultLayout/about"
    | "/_defaultLayout/profile"
    | "/_defaultLayout/stats"
    | "/_defaultLayout/uses"
    | "/_defaultLayout/"
    | "/_defaultLayout/blog/$articleId"
    | "/_defaultLayout/bookmarks/$bookmarkId"
    | "/_defaultLayout/projects/$projectId"
    | "/_defaultLayout/snippets/$snippetId"
    | "/_dashboardLayout/dashboard/"
    | "/_defaultLayout/blog/"
    | "/_defaultLayout/bookmarks/"
    | "/_defaultLayout/projects/"
    | "/_defaultLayout/snippets/"
    | "/_dashboardLayout/dashboard/blog/create"
    | "/_dashboardLayout/dashboard/experiences/create"
    | "/_dashboardLayout/dashboard/projects/create"
    | "/_dashboardLayout/dashboard/snippets/create"
    | "/_dashboardLayout/dashboard/blog/"
    | "/_dashboardLayout/dashboard/experiences/"
    | "/_dashboardLayout/dashboard/projects/"
    | "/_dashboardLayout/dashboard/snippets/"
    | "/_dashboardLayout/dashboard/users/"
    | "/_dashboardLayout/dashboard/blog/$articleId/edit"
    | "/_dashboardLayout/dashboard/experiences/$experienceId/edit"
    | "/_dashboardLayout/dashboard/projects/$projectId/edit"
    | "/_dashboardLayout/dashboard/snippets/$snippetId/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren;
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren;
  DefaultLayoutRoute: typeof DefaultLayoutRouteWithChildren;
}
export interface FileServerRoutesByFullPath {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/trpc/$": typeof ApiTrpcSplatServerRoute;
  "/api/contact": typeof ApiContactIndexServerRoute;
  "/api/stats/github/activity": typeof ApiStatsGithubActivityServerRoute;
  "/api/stats/github": typeof ApiStatsGithubIndexServerRoute;
}
export interface FileServerRoutesByTo {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/trpc/$": typeof ApiTrpcSplatServerRoute;
  "/api/contact": typeof ApiContactIndexServerRoute;
  "/api/stats/github/activity": typeof ApiStatsGithubActivityServerRoute;
  "/api/stats/github": typeof ApiStatsGithubIndexServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/trpc/$": typeof ApiTrpcSplatServerRoute;
  "/api/contact/": typeof ApiContactIndexServerRoute;
  "/api/stats/github/activity": typeof ApiStatsGithubActivityServerRoute;
  "/api/stats/github/": typeof ApiStatsGithubIndexServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths:
    | "/api/auth/$"
    | "/api/trpc/$"
    | "/api/contact"
    | "/api/stats/github/activity"
    | "/api/stats/github";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to:
    | "/api/auth/$"
    | "/api/trpc/$"
    | "/api/contact"
    | "/api/stats/github/activity"
    | "/api/stats/github";
  id:
    | "__root__"
    | "/api/auth/$"
    | "/api/trpc/$"
    | "/api/contact/"
    | "/api/stats/github/activity"
    | "/api/stats/github/";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute;
  ApiTrpcSplatServerRoute: typeof ApiTrpcSplatServerRoute;
  ApiContactIndexServerRoute: typeof ApiContactIndexServerRoute;
  ApiStatsGithubActivityServerRoute: typeof ApiStatsGithubActivityServerRoute;
  ApiStatsGithubIndexServerRoute: typeof ApiStatsGithubIndexServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_defaultLayout": {
      id: "/_defaultLayout";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof DefaultLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_dashboardLayout": {
      id: "/_dashboardLayout";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof DashboardLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authLayout": {
      id: "/_authLayout";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_defaultLayout/": {
      id: "/_defaultLayout/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof DefaultLayoutIndexRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_defaultLayout/uses": {
      id: "/_defaultLayout/uses";
      path: "/uses";
      fullPath: "/uses";
      preLoaderRoute: typeof DefaultLayoutUsesRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_defaultLayout/stats": {
      id: "/_defaultLayout/stats";
      path: "/stats";
      fullPath: "/stats";
      preLoaderRoute: typeof DefaultLayoutStatsRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_defaultLayout/profile": {
      id: "/_defaultLayout/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof DefaultLayoutProfileRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_defaultLayout/about": {
      id: "/_defaultLayout/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof DefaultLayoutAboutRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_authLayout/signin": {
      id: "/_authLayout/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof AuthLayoutSigninRouteImport;
      parentRoute: typeof AuthLayoutRoute;
    };
    "/_defaultLayout/snippets/": {
      id: "/_defaultLayout/snippets/";
      path: "/snippets";
      fullPath: "/snippets";
      preLoaderRoute: typeof DefaultLayoutSnippetsIndexRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_defaultLayout/projects/": {
      id: "/_defaultLayout/projects/";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof DefaultLayoutProjectsIndexRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_defaultLayout/bookmarks/": {
      id: "/_defaultLayout/bookmarks/";
      path: "/bookmarks";
      fullPath: "/bookmarks";
      preLoaderRoute: typeof DefaultLayoutBookmarksIndexRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_defaultLayout/blog/": {
      id: "/_defaultLayout/blog/";
      path: "/blog";
      fullPath: "/blog";
      preLoaderRoute: typeof DefaultLayoutBlogIndexRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_dashboardLayout/dashboard/": {
      id: "/_dashboardLayout/dashboard/";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardLayoutDashboardIndexRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_defaultLayout/snippets/$snippetId": {
      id: "/_defaultLayout/snippets/$snippetId";
      path: "/snippets/$snippetId";
      fullPath: "/snippets/$snippetId";
      preLoaderRoute: typeof DefaultLayoutSnippetsSnippetIdRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_defaultLayout/projects/$projectId": {
      id: "/_defaultLayout/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof DefaultLayoutProjectsProjectIdRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_defaultLayout/bookmarks/$bookmarkId": {
      id: "/_defaultLayout/bookmarks/$bookmarkId";
      path: "/bookmarks/$bookmarkId";
      fullPath: "/bookmarks/$bookmarkId";
      preLoaderRoute: typeof DefaultLayoutBookmarksBookmarkIdRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_defaultLayout/blog/$articleId": {
      id: "/_defaultLayout/blog/$articleId";
      path: "/blog/$articleId";
      fullPath: "/blog/$articleId";
      preLoaderRoute: typeof DefaultLayoutBlogArticleIdRouteImport;
      parentRoute: typeof DefaultLayoutRoute;
    };
    "/_dashboardLayout/dashboard/users/": {
      id: "/_dashboardLayout/dashboard/users/";
      path: "/dashboard/users";
      fullPath: "/dashboard/users";
      preLoaderRoute: typeof DashboardLayoutDashboardUsersIndexRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboardLayout/dashboard/snippets/": {
      id: "/_dashboardLayout/dashboard/snippets/";
      path: "/dashboard/snippets";
      fullPath: "/dashboard/snippets";
      preLoaderRoute: typeof DashboardLayoutDashboardSnippetsIndexRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboardLayout/dashboard/projects/": {
      id: "/_dashboardLayout/dashboard/projects/";
      path: "/dashboard/projects";
      fullPath: "/dashboard/projects";
      preLoaderRoute: typeof DashboardLayoutDashboardProjectsIndexRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboardLayout/dashboard/experiences/": {
      id: "/_dashboardLayout/dashboard/experiences/";
      path: "/dashboard/experiences";
      fullPath: "/dashboard/experiences";
      preLoaderRoute: typeof DashboardLayoutDashboardExperiencesIndexRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboardLayout/dashboard/blog/": {
      id: "/_dashboardLayout/dashboard/blog/";
      path: "/dashboard/blog";
      fullPath: "/dashboard/blog";
      preLoaderRoute: typeof DashboardLayoutDashboardBlogIndexRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboardLayout/dashboard/snippets/create": {
      id: "/_dashboardLayout/dashboard/snippets/create";
      path: "/dashboard/snippets/create";
      fullPath: "/dashboard/snippets/create";
      preLoaderRoute: typeof DashboardLayoutDashboardSnippetsCreateRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboardLayout/dashboard/projects/create": {
      id: "/_dashboardLayout/dashboard/projects/create";
      path: "/dashboard/projects/create";
      fullPath: "/dashboard/projects/create";
      preLoaderRoute: typeof DashboardLayoutDashboardProjectsCreateRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboardLayout/dashboard/experiences/create": {
      id: "/_dashboardLayout/dashboard/experiences/create";
      path: "/dashboard/experiences/create";
      fullPath: "/dashboard/experiences/create";
      preLoaderRoute: typeof DashboardLayoutDashboardExperiencesCreateRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboardLayout/dashboard/blog/create": {
      id: "/_dashboardLayout/dashboard/blog/create";
      path: "/dashboard/blog/create";
      fullPath: "/dashboard/blog/create";
      preLoaderRoute: typeof DashboardLayoutDashboardBlogCreateRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboardLayout/dashboard/snippets/$snippetId/edit": {
      id: "/_dashboardLayout/dashboard/snippets/$snippetId/edit";
      path: "/dashboard/snippets/$snippetId/edit";
      fullPath: "/dashboard/snippets/$snippetId/edit";
      preLoaderRoute: typeof DashboardLayoutDashboardSnippetsSnippetIdEditRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboardLayout/dashboard/projects/$projectId/edit": {
      id: "/_dashboardLayout/dashboard/projects/$projectId/edit";
      path: "/dashboard/projects/$projectId/edit";
      fullPath: "/dashboard/projects/$projectId/edit";
      preLoaderRoute: typeof DashboardLayoutDashboardProjectsProjectIdEditRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboardLayout/dashboard/experiences/$experienceId/edit": {
      id: "/_dashboardLayout/dashboard/experiences/$experienceId/edit";
      path: "/dashboard/experiences/$experienceId/edit";
      fullPath: "/dashboard/experiences/$experienceId/edit";
      preLoaderRoute: typeof DashboardLayoutDashboardExperiencesExperienceIdEditRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboardLayout/dashboard/blog/$articleId/edit": {
      id: "/_dashboardLayout/dashboard/blog/$articleId/edit";
      path: "/dashboard/blog/$articleId/edit";
      fullPath: "/dashboard/blog/$articleId/edit";
      preLoaderRoute: typeof DashboardLayoutDashboardBlogArticleIdEditRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/api/contact/": {
      id: "/api/contact/";
      path: "/api/contact";
      fullPath: "/api/contact";
      preLoaderRoute: typeof ApiContactIndexServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/trpc/$": {
      id: "/api/trpc/$";
      path: "/api/trpc/$";
      fullPath: "/api/trpc/$";
      preLoaderRoute: typeof ApiTrpcSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/stats/github/": {
      id: "/api/stats/github/";
      path: "/api/stats/github";
      fullPath: "/api/stats/github";
      preLoaderRoute: typeof ApiStatsGithubIndexServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/stats/github/activity": {
      id: "/api/stats/github/activity";
      path: "/api/stats/github/activity";
      fullPath: "/api/stats/github/activity";
      preLoaderRoute: typeof ApiStatsGithubActivityServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutSigninRoute: typeof AuthLayoutSigninRoute;
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutSigninRoute: AuthLayoutSigninRoute,
};

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
);

interface DashboardLayoutRouteChildren {
  DashboardLayoutDashboardIndexRoute: typeof DashboardLayoutDashboardIndexRoute;
  DashboardLayoutDashboardBlogCreateRoute: typeof DashboardLayoutDashboardBlogCreateRoute;
  DashboardLayoutDashboardExperiencesCreateRoute: typeof DashboardLayoutDashboardExperiencesCreateRoute;
  DashboardLayoutDashboardProjectsCreateRoute: typeof DashboardLayoutDashboardProjectsCreateRoute;
  DashboardLayoutDashboardSnippetsCreateRoute: typeof DashboardLayoutDashboardSnippetsCreateRoute;
  DashboardLayoutDashboardBlogIndexRoute: typeof DashboardLayoutDashboardBlogIndexRoute;
  DashboardLayoutDashboardExperiencesIndexRoute: typeof DashboardLayoutDashboardExperiencesIndexRoute;
  DashboardLayoutDashboardProjectsIndexRoute: typeof DashboardLayoutDashboardProjectsIndexRoute;
  DashboardLayoutDashboardSnippetsIndexRoute: typeof DashboardLayoutDashboardSnippetsIndexRoute;
  DashboardLayoutDashboardUsersIndexRoute: typeof DashboardLayoutDashboardUsersIndexRoute;
  DashboardLayoutDashboardBlogArticleIdEditRoute: typeof DashboardLayoutDashboardBlogArticleIdEditRoute;
  DashboardLayoutDashboardExperiencesExperienceIdEditRoute: typeof DashboardLayoutDashboardExperiencesExperienceIdEditRoute;
  DashboardLayoutDashboardProjectsProjectIdEditRoute: typeof DashboardLayoutDashboardProjectsProjectIdEditRoute;
  DashboardLayoutDashboardSnippetsSnippetIdEditRoute: typeof DashboardLayoutDashboardSnippetsSnippetIdEditRoute;
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutDashboardIndexRoute: DashboardLayoutDashboardIndexRoute,
  DashboardLayoutDashboardBlogCreateRoute:
    DashboardLayoutDashboardBlogCreateRoute,
  DashboardLayoutDashboardExperiencesCreateRoute:
    DashboardLayoutDashboardExperiencesCreateRoute,
  DashboardLayoutDashboardProjectsCreateRoute:
    DashboardLayoutDashboardProjectsCreateRoute,
  DashboardLayoutDashboardSnippetsCreateRoute:
    DashboardLayoutDashboardSnippetsCreateRoute,
  DashboardLayoutDashboardBlogIndexRoute:
    DashboardLayoutDashboardBlogIndexRoute,
  DashboardLayoutDashboardExperiencesIndexRoute:
    DashboardLayoutDashboardExperiencesIndexRoute,
  DashboardLayoutDashboardProjectsIndexRoute:
    DashboardLayoutDashboardProjectsIndexRoute,
  DashboardLayoutDashboardSnippetsIndexRoute:
    DashboardLayoutDashboardSnippetsIndexRoute,
  DashboardLayoutDashboardUsersIndexRoute:
    DashboardLayoutDashboardUsersIndexRoute,
  DashboardLayoutDashboardBlogArticleIdEditRoute:
    DashboardLayoutDashboardBlogArticleIdEditRoute,
  DashboardLayoutDashboardExperiencesExperienceIdEditRoute:
    DashboardLayoutDashboardExperiencesExperienceIdEditRoute,
  DashboardLayoutDashboardProjectsProjectIdEditRoute:
    DashboardLayoutDashboardProjectsProjectIdEditRoute,
  DashboardLayoutDashboardSnippetsSnippetIdEditRoute:
    DashboardLayoutDashboardSnippetsSnippetIdEditRoute,
};

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
);

interface DefaultLayoutRouteChildren {
  DefaultLayoutAboutRoute: typeof DefaultLayoutAboutRoute;
  DefaultLayoutProfileRoute: typeof DefaultLayoutProfileRoute;
  DefaultLayoutStatsRoute: typeof DefaultLayoutStatsRoute;
  DefaultLayoutUsesRoute: typeof DefaultLayoutUsesRoute;
  DefaultLayoutIndexRoute: typeof DefaultLayoutIndexRoute;
  DefaultLayoutBlogArticleIdRoute: typeof DefaultLayoutBlogArticleIdRoute;
  DefaultLayoutBookmarksBookmarkIdRoute: typeof DefaultLayoutBookmarksBookmarkIdRoute;
  DefaultLayoutProjectsProjectIdRoute: typeof DefaultLayoutProjectsProjectIdRoute;
  DefaultLayoutSnippetsSnippetIdRoute: typeof DefaultLayoutSnippetsSnippetIdRoute;
  DefaultLayoutBlogIndexRoute: typeof DefaultLayoutBlogIndexRoute;
  DefaultLayoutBookmarksIndexRoute: typeof DefaultLayoutBookmarksIndexRoute;
  DefaultLayoutProjectsIndexRoute: typeof DefaultLayoutProjectsIndexRoute;
  DefaultLayoutSnippetsIndexRoute: typeof DefaultLayoutSnippetsIndexRoute;
}

const DefaultLayoutRouteChildren: DefaultLayoutRouteChildren = {
  DefaultLayoutAboutRoute: DefaultLayoutAboutRoute,
  DefaultLayoutProfileRoute: DefaultLayoutProfileRoute,
  DefaultLayoutStatsRoute: DefaultLayoutStatsRoute,
  DefaultLayoutUsesRoute: DefaultLayoutUsesRoute,
  DefaultLayoutIndexRoute: DefaultLayoutIndexRoute,
  DefaultLayoutBlogArticleIdRoute: DefaultLayoutBlogArticleIdRoute,
  DefaultLayoutBookmarksBookmarkIdRoute: DefaultLayoutBookmarksBookmarkIdRoute,
  DefaultLayoutProjectsProjectIdRoute: DefaultLayoutProjectsProjectIdRoute,
  DefaultLayoutSnippetsSnippetIdRoute: DefaultLayoutSnippetsSnippetIdRoute,
  DefaultLayoutBlogIndexRoute: DefaultLayoutBlogIndexRoute,
  DefaultLayoutBookmarksIndexRoute: DefaultLayoutBookmarksIndexRoute,
  DefaultLayoutProjectsIndexRoute: DefaultLayoutProjectsIndexRoute,
  DefaultLayoutSnippetsIndexRoute: DefaultLayoutSnippetsIndexRoute,
};

const DefaultLayoutRouteWithChildren = DefaultLayoutRoute._addFileChildren(
  DefaultLayoutRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  DefaultLayoutRoute: DefaultLayoutRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiTrpcSplatServerRoute: ApiTrpcSplatServerRoute,
  ApiContactIndexServerRoute: ApiContactIndexServerRoute,
  ApiStatsGithubActivityServerRoute: ApiStatsGithubActivityServerRoute,
  ApiStatsGithubIndexServerRoute: ApiStatsGithubIndexServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
